apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup-aws
  namespace: mysql
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:  
          containers:
            - name: mysql-backup-aws
              image: docker.io/ashafqat/mysql-backup-aws:v1.3
              imagePullPolicy: IfNotPresent  
              command:
              - /bin/sh
              args:
              - -c
              - /root/backup.sh
              env:
                - name: DB_HOST
                  value: mysql-service
                - name: DB_NAME
                  value: book-management-db
                - name: DB_USER
                  value: root
                - name: DB_PASS
                  value: winterblabla
                - name: S3_BUCKET
                  value: s3://bucketname
                - name: AWS_ACCESS_KEY_ID
                  value: blablabla
                - name: AWS_SECRET_ACCESS_KEY
                  value: giablablabla
                - name: AWS_DEFAULT_REGION
                  value: us-east-1                                                    
          restartPolicy: OnFailure
